language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - libboost-all-dev

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

install:
  # Linux Setup
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="/usr/bin/g++-6"                                                               ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC="/usr/bin/gcc-6"                                                                ;fi
  - git clone https://github.com/physycom/sysconfig.git
  - export WORKSPACE=$(pwd)
  - mkdir build && cd build

script:
  - cmake ..
  - cmake --build .
